version: "3.3"

services:
  code-server:
    image: linuxserver/code-server:$CODE_SERVER_VERSION
    container_name: code-server
    hostname: code-server
    domainname: $DOMAIN_NAME
    environment:
      - PUID=$USER_PUID
      - PGID=$USER_PGID
      - TZ=America/Sao_Paulo
      - PASSWORD=$CODE_SERVER_PASSWORD
      - SUDO_PASSWORD=$CODE_SERVER_SUDO_PASSWORD
      - PROXY_DOMAIN=code-server.$DOMAIN_NAME
    volumes:
      - $SHARED_FOLDER/CodeServer/Config:/config
      - $SHARED_FOLDER/Code:/code
    ports:
      - 8443:8443
    restart: unless-stopped
    networks:
      - code-server

networks:
  code-server:
