version: "2"

services:
  jdownloader2:
    image: jlesage/jdownloader-2:$JDOWNLOADER2_VERSION
    container_name: jdownloader2
    hostname: jdownloader2
    domainname: $DOMAIN_NAME
    ports:
      - 5800:5800
      - 5900:5900
      - 3129:3129
    volumes:
      - $SHARED_FOLDER/JDownloader2/Config:/config
      - $SHARED_FOLDER/Downloads:/output
    restart: unless-stopped
