version: "2"

services:
  bitwarden:
    image: bitwardenrs/server:${BITWARDEN_VERSION}
    container_name: bitwarden
    hostname: bitwarden
    domainname: ${DOMAIN_NAME}
    volumes:
      - ${SHARED_FOLDER}/Bitwarden/Data:/data
    ports:
      - 8080:80
    restart: unless-stopped
