version: "2"
services:
  jDownloader2:
    image: jlesage/jdownloader-2:${JDOWNLOADER2_VERSION}
    container_name: jDownloader2
    hostname: jDownloader2
    domainname: ${DOMAIN_NAME}
    ports:
      - 5800:5800
      - 5900:5900
      - 3129:3129
    volumes:
      - ${SHARED_FOLDER}/JDownloader2/Config:/config
      - ${PATH_TO_DOWNLOADS}:/output
    restart: unless-stopped