version: "3.3"

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    hostname: jenkins
    domainname: ${MY_DOMAINNAME}
    networks:
      - jenkins_network
    ports:
      - 8081:8080
      - 5000:5000
    volumes:
      - jenkins_data:/var/jenkins_home
    restart: unless-stopped

networks:
  jenkins_network:
    driver: bridge

volumes:
  jenkins_data:
