version: "3"

services:
  grafana:
    image: grafana/grafana:$GRAFANA_VERSION
    container_name: grafana
    hostname: grafana
    domainname: $DOMAIN_NAME
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
