version: "2.4"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:${PORTAINER_VERSION}
    hostname: portainer-${MACHINE_HOST_NAME}
    domainname: ${DOMAIN_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped
    ports:
      - 9000:9000

volumes:
  portainer_data:
    driver: bridge
