version: "3.3"

services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:8.9.1-community
    hostname: sonarqube
    domainname: ${MY_DOMAINNAME}
    depends_on:
      - postgres
    ports:
      - 9000:9000
    networks:
      - sonarqube_network
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    restart: unless-stopped

  postgres:
    image: postgres
    container_name: postgres-sq
    networks:
      - sonarqube_network
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  sonarqube_network:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions:
  postgresql:
  postgresql_data:
